// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.startupRolloutPrefs.browser.partnerlink.useAttributionURL", true);
user_pref("app.normandy.startupRolloutPrefs.browser.topsites.contile.enabled", true);
user_pref("app.normandy.startupRolloutPrefs.browser.topsites.experiment.ebay-2020-1", true);
user_pref("app.normandy.startupRolloutPrefs.browser.topsites.useRemoteSetting", true);
user_pref("app.normandy.user_id", "b7f85d1a-5ea0-404f-b723-33bc938aad1e");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.background.previous.reasons", "[\"app.update.background.enabled=false\"]");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1629198485);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1629198481);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir2.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1629198485);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 116);
user_pref("browser.newtabpage.activity-stream.impressionId", "{1924f4ce-6aed-43ef-a51e-52f998a74907}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1629198482);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1629198495800");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1629220095800");
user_pref("browser.search.region", "FR");
user_pref("browser.sessionstore.resume_session_once", true);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1629198491");
user_pref("browser.startup.homepage_override.buildID", "20210804193234");
user_pref("browser.startup.homepage_override.mstone", "91.0");
user_pref("browser.startup.lastColdStartupCheck", 1629198487);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1629198491521");
user_pref("distribution.iniFile.exists.appversion", "91.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "FR");
user_pref("dom.push.userAgentID", "5c507096570144b69a0ed2a2389111a6");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210804193234");
user_pref("extensions.lastAppVersion", "91.0");
user_pref("extensions.lastPlatformVersion", "91.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"1a93d65b-4721-4549-9924-c3c1f46aa8de\",\"formautofill@mozilla.org\":\"9c1ea4dd-f339-4888-8b9d-e70a294ef137\",\"pictureinpicture@mozilla.org\":\"02ab6fc5-9f00-4ebf-a889-59a4b2897aa9\",\"screenshots@mozilla.org\":\"c89cbcbd-fc9f-4634-9850-d1dd4e7d7dab\",\"webcompat-reporter@mozilla.org\":\"de0777bd-06e8-4908-bcb9-7c851085e85a\",\"webcompat@mozilla.org\":\"b704e523-8588-4e8e-b0be-5b6475881e21\",\"default-theme@mozilla.org\":\"e64ca345-85c5-4977-b976-799650a3d36a\",\"google@search.mozilla.org\":\"3dd63e77-7686-4321-be2c-b2b5665973b4\",\"wikipedia@search.mozilla.org\":\"c2890965-c7d7-488b-a7c4-ad85a1934d45\",\"bing@search.mozilla.org\":\"64f4f6a8-46c8-4304-a2b4-e5cfab4c6c0b\",\"amazon@search.mozilla.org\":\"feb8e6d2-acca-4ac7-a7cb-2e0a53e70aed\",\"ddg@search.mozilla.org\":\"78348420-6a08-4e6d-8f06-d27f69b81af2\",\"ebay@search.mozilla.org\":\"f7a7f4ca-1add-4b62-b675-cdb3dda62254\",\"qwant@search.mozilla.org\":\"67759d94-250f-444f-a6e3-f07dd2853b9f\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1629198491);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gfx-shader-check.build-version", "20210804193234");
user_pref("gfx-shader-check.device-id", "0x0116");
user_pref("gfx-shader-check.driver-version", "9.17.10.4459");
user_pref("gfx-shader-check.ptr-size", 8);
user_pref("gfx.crash-guard.status.wmfvpxvideo", 2);
user_pref("gfx.crash-guard.wmfvpxvideo.appVersion", "91.0");
user_pref("gfx.crash-guard.wmfvpxvideo.deviceID", "0x0116");
user_pref("gfx.crash-guard.wmfvpxvideo.driverVersion", "9.17.10.4459");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("nimbus.syncdefaultsstore.upgradeDialog", "{\"slug\":\"upgradeDialog-defaultEnabled\",\"enabled\":true,\"targeting\":\"true\",\"variables\":{},\"description\":\"Turn on upgradeDialog by default for all users\"}");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.device-id", "0x0116");
user_pref("sanity-test.driver-version", "9.17.10.4459");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20210804193234");
user_pref("sanity-test.webrender.force-disabled", false);
user_pref("security.sandbox.content.tempDirSuffix", "{dc394a29-6202-4966-a3fc-b2a9aa8dc75f}");
user_pref("toolkit.startup.last_success", 1629198475);
user_pref("toolkit.telemetry.cachedClientID", "f22f13ea-e7ba-434c-915f-3a5e5d30ae89");
user_pref("toolkit.telemetry.previousBuildID", "20210804193234");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
